import { Category } from '@/types/wallet';
import { colors } from './colors';

export const defaultCategories: Category[] = [
  // Income categories
  {
    id: 'income-salary',
    name: 'Salary',
    type: 'income',
    icon: 'briefcase',
    color: colors.success,
    isDefault: true,
  },
  {
    id: 'income-business',
    name: 'Business',
    type: 'income',
    icon: 'building',
    color: colors.success,
    isDefault: true,
  },
  {
    id: 'income-investments',
    name: 'Investments',
    type: 'income',
    icon: 'trending-up',
    color: colors.success,
    isDefault: true,
  },
  {
    id: 'income-gifts',
    name: 'Gifts',
    type: 'income',
    icon: 'gift',
    color: colors.success,
    isDefault: true,
  },
  {
    id: 'income-other',
    name: 'Other Income',
    type: 'income',
    icon: 'plus-circle',
    color: colors.success,
    isDefault: true,
  },
  
  // Expense categories
  {
    id: 'expense-housing',
    name: 'Housing',
    type: 'expense',
    icon: 'home',
    color: colors.danger,
    isDefault: true,
  },
  {
    id: 'expense-food',
    name: 'Food & Dining',
    type: 'expense',
    icon: 'utensils',
    color: colors.danger,
    isDefault: true,
  },
  {
    id: 'expense-transportation',
    name: 'Transportation',
    type: 'expense',
    icon: 'car',
    color: colors.danger,
    isDefault: true,
  },
  {
    id: 'expense-utilities',
    name: 'Utilities',
    type: 'expense',
    icon: 'zap',
    color: colors.danger,
    isDefault: true,
  },
  {
    id: 'expense-shopping',
    name: 'Shopping',
    type: 'expense',
    icon: 'shopping-bag',
    color: colors.danger,
    isDefault: true,
  },
  {
    id: 'expense-entertainment',
    name: 'Entertainment',
    type: 'expense',
    icon: 'film',
    color: colors.danger,
    isDefault: true,
  },
  {
    id: 'expense-health',
    name: 'Health & Medical',
    type: 'expense',
    icon: 'activity',
    color: colors.danger,
    isDefault: true,
  },
  {
    id: 'expense-education',
    name: 'Education',
    type: 'expense',
    icon: 'book',
    color: colors.danger,
    isDefault: true,
  },
  {
    id: 'expense-personal',
    name: 'Personal Care',
    type: 'expense',
    icon: 'user',
    color: colors.danger,
    isDefault: true,
  },
  {
    id: 'expense-subscriptions',
    name: 'Subscriptions',
    type: 'expense',
    icon: 'repeat',
    color: colors.danger,
    isDefault: true,
  },
  {
    id: 'expense-other',
    name: 'Other Expenses',
    type: 'expense',
    icon: 'more-horizontal',
    color: colors.danger,
    isDefault: true,
  },
];